package com.myspace.agenda;

import com.myspace.model.MyFact;

rule "Rule A"
enabled false
when
   $fact : MyFact()
then
   modify($fact) { setField1(true) };
   System.out.format("%s %s\n", kcontext.getRule().getName(), $fact);
   drools.setFocus("Group B");
end

rule "Rule B"
agenda-group "Group B"
enabled false
when
   $fact : MyFact()
then
   modify($fact) { setField1(false) };
   System.out.format("%s %s\n", kcontext.getRule().getName(), $fact);
end