package com.myspace.salience;

import com.myspace.model.MyFact;

rule "Rule A"
salience 95
when
    $fact : MyFact()
then
   modify($fact) { setField1(true) };
   System.out.format("%s %s\n", kcontext.getRule().getName(), $fact);
end

rule "Rule B"
salience 100
when
   $fact : MyFact()
then
   modify($fact) { setField1(false) };
   System.out.format("%s %s\n", kcontext.getRule().getName(), $fact);
end